name: '${project_name}'
version: '${version}'
author: '${authors}'
description: '${project_description}'
website: '${homepage_url}'
main: '${group_id}.${project_id}.platforms.BukkitPlugin'
depend: [ TaterLib ]
depends: [ TaterLib ]
softdepends: [ ]
api-version: 1.21
folia-supported: true
commands:
  tvc:
    description: Example command
    usage: /tvc
    permission: tvc.command
